version: '3.9'
services:
  rest-with-spring-boot:
    image: vieira2v/rest-with-spring-boot
    restart: always
    build:
      context: .
    working_dir: /rest-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://rest-with-spring-boot.cl660weswdnt.us-east-1.rds.amazonaws.com:5432/rest_with_spring_boot
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    networks:
      - example-network
networks:
  example-network:
    driver: bridge