version: '3.9'
services:
  db:
    image: postgres:17beta3
    command: postgres
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mvx1064@
      POSTGRES_DB: rest-with-spring-boot
    ports:
      - "5433:5432"
    networks:
      - example-network

  rest-with-spring-boot:
    image: vieira2v/rest-with-spring-boot
    restart: always
    build:
      context: .
    working_dir: /rest-with-spring-boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/rest-with-spring-boot
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: mvx1064@
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - example-network
networks:
  example-network:
    driver: bridge