cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://example.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: mvx1064@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
