INSERT INTO person (first_name, last_name, gender, address, enabled) VALUES
('Guglielma', 'Milmore', 'Female', '7 Roth Road', false),
('Eden', 'Hasselby', 'Female', '86518 Hayes Pass', true),
('Ailbert', 'Burgen', 'Male', '6067 Anhalt Center', false),
('Dania', 'Butte', 'Female', '07 Brickson Park Road', true),
('Quill', 'Paumier', 'Male', '8 Service Road', false),
('Angela', 'Ansteys', 'Female', '164 Pond Center', true),
('Chrissie', 'Zahor', 'Female', '2 Springs Alley', true),
('Matias', 'Cassedy', 'Male', '2 Darwin Junction', true),
('Cacilie', 'Descroix', 'Male', '388 5th Court', true),
('Evangelin', 'Kingsnode', 'Male', '82778 Mariners Cove Parkway', false),
('Pinchas', 'Mallabar', 'Male', '4 Village Pass', false),
('Josh', 'Yanson', 'Male', '2 Ramsey Point', true),
('Malissia', 'Iiannoni', 'Female', '2 2nd Center', true),
('Sigfried', 'Bemwell', 'Male', '26 Gale Pass', false),
('Toby', 'Theobold', 'Male', '8300 Ridgeway Park', true),
('Maryjane', 'Loyns', 'Male', '89 Rutledge Street', false),
('Inger', 'Dehn', 'Male', '03 7th Avenue', false),
('Colline', 'Paradyce', 'Female', '67 Hagan Center', false),
('Bruce', 'MacCaughan', 'Male', '23 Union Plaza', false),
('Dunn', 'Galea', 'Male', '5 Merrick Junction', true),
('Tannie', 'Frapwell', 'Male', '71996 Pennsylvania Street', true),
('Millie', 'Parkhouse', 'Female', '36 Nelson Point', true),
('Carroll', 'Klimsch', 'Male', '233 Homewood Drive', true),
('Lionel', 'Holwell', 'Male', '3924 Oak Park', true),
('Willa', 'Carlin', 'Female', '4 Sachs Hill', false),
('Barnie', 'Land', 'Male', '08 Ludington Way', false),
('Burnaby', 'Otteridge', 'Female', '38439 Butternut Drive', true),
('Dru', 'Holley', 'Male', '078 Debra Crossing', true),
('Christal', 'Wyman', 'Female', '9 Rutledge Circle', false),
('Arvin', 'Gallymore', 'Male', '263 Carey Center', false),
('Gamaliel', 'Motten', 'Male', '272 Helena Parkway', false),
('Orelee', 'Folbig', 'Male', '025 Park Meadow Junction', true),
('Dot', 'Bewsey', 'Female', '1 Harbort Junction', true),
('Joell', 'Hassur', 'Female', '9314 Mallory Crossing', true),
('Archer', 'Harner', 'Male', '653 Bunting Point', true),
('Wyndham', 'Faltskog', 'Male', '9011 Crescent Oaks Plaza', true),
('Stanwood', 'Rainville', 'Male', '21404 Moland Road', false),
('Matias', 'Vant', 'Male', '859 Blaine Place', false),
('Hamid', 'Bilham', 'Male', '6 Moose Point', true),
('Euell', 'MacAndie', 'Male', '257 Sommers Crossing', true),
('Hamnet', 'Woodburn', 'Male', '97 Tony Court', true),
('Ebba', 'Schirak', 'Female', '501 Elka Center', false),
('Mart', 'Anderbrugge', 'Male', '7876 Amoth Crossing', true),
('Silvio', 'Romans', 'Male', '7489 Kings Plaza', false),
('Kim', 'Craik', 'Female', '401 Hollow Ridge Crossing', true),
('Renell', 'Strevens', 'Female', '8231 Barby Road', true),
('Tamqrah', 'Garner', 'Female', '51888 Bonner Terrace', true),
('Morrie', 'Glader', 'Male', '54491 Commercial Trail', false),
('Jamison', 'Landsborough', 'Male', '17 Quincy Trail', false),
('Clo', 'Pritchett', 'Female', '4 Shelley Alley', true),
('Jude', 'Laugharne', 'Male', '6474 Twin Pines Hill', false),
('Burlie', 'Coathup', 'Male', '7 Dwight Way', false),
('Lisbeth', 'Toxell', 'Female', '48 Dovetail Point', true),
('Emlen', 'Nurny', 'Male', '44 Waxwing Park', true),
('Aymer', 'Hubane', 'Male', '23286 Arkansas Lane', true),
('Carrol', 'Brosoli', 'Male', '6 Maple Crossing', true),
('Leila', 'Vidgeon', 'Female', '30086 Melrose Hill', false),
('Gardener', 'Atwool', 'Male', '83572 Cardinal Way', false),
('Darwin', 'Rihosek', 'Male', '662 Huxley Crossing', false),
('Dottie', 'Mancktelow', 'Female', '4 Londonderry Avenue', true),
('Lilian', 'Bartel', 'Female', '0 Schlimgen Hill', true),
('Abbe', 'Kytley', 'Male', '69618 Aberg Court', true),
('Laure', 'Cicchillo', 'Female', '715 Mallory Hill', false),
('Lyndel', 'Yatman', 'Female', '648 Dexter Place', false),
('Janka', 'O''Heaney', 'Female', '9982 Jenifer Center', true),
('Hubert', 'Pietesch', 'Male', '96 Texas Alley', true),
('Annalee', 'Visco', 'Female', '193 Gulseth Hill', false),
('Courtney', 'Barnhill', 'Female', '7371 Gina Avenue', false),
('Laurianne', 'Draisey', 'Female', '156 Melody Alley', true),
('Oberon', 'Chantrell', 'Male', '656 2nd Point', true),
('Iormina', 'Sinkins', 'Female', '95 Rowland Hill', false),
('Melony', 'Curneen', 'Female', '398 Ruskin Parkway', true),
('Che', 'McGriele', 'Male', '4 Pearson Trail', true),
('Walton', 'Bailiss', 'Male', '86 Clyde Gallagher Circle', false),
('Kay', 'Goadby', 'Female', '37975 Summer Ridge Terrace', false),
('Yancey', 'Gauntley', 'Male', '19 Kings Point', false),
('Perla', 'Mayzes', 'Female', '33990 Crowley Junction', false),
('Henrie', 'Bausor', 'Female', '73 Stang Drive', true),
('Malynda', 'Ledwidge', 'Female', '7 Evergreen Drive', true),
('Dag', 'Dysart', 'Male', '01 Victoria Pass', true),
('Trip', 'Kryszkiecicz', 'Male', '748 Kipling Parkway', false),
('Wood', 'Fairhead', 'Male', '44 Maywood Plaza', true),
('Northrop', 'Turl', 'Male', '4 Glacier Hill Park', true),
('Isa', 'Devonish', 'Male', '32502 Debs Park', true),
('Cori', 'Revie', 'Female', '8388 Melrose Pass', true),
('Willi', 'Sheering', 'Female', '15 Dexter Junction', false),
('Ingmar', 'Redolfi', 'Male', '4697 Bunker Hill Point', false),
('Faunie', 'Dunne', 'Female', '71032 Basil Crossing', false),
('Shelly', 'Wandtke', 'Female', '5209 Dapin Lane', false),
('Jacinthe', 'Candy', 'Female', '48 Green Place', false),
('Seymour', 'McCue', 'Male', '6375 Mayer Place', true),
('Adelaide', 'Rawlinson', 'Female', '71202 Warner Drive', false),
('Stinky', 'Mathivet', 'Male', '940 Nancy Crossing', true),
('Selby', 'Weatherup', 'Female', '56 Gerald Court', true),
('Diana', 'Alpe', 'Female', '9 Upham Avenue', true),
('Fletch', 'Escala', 'Male', '06 Hauk Trail', false),
('Roi', 'Savary', 'Male', '9 Del Mar Park', true),
('Melisande', 'Doumer', 'Female', '2388 Larry Park', false),
('Horace', 'Lambkin', 'Male', '20094 Superior Court', true),
('Christine', 'Rydeard', 'Female', '821 Jackson Place', true),
('Bertina', 'Matchitt', 'Female', '287 Raven Park', true),
('Ricki', 'Absolom', 'Male', '1 Nova Court', false),
('Gamaliel', 'Fincham', 'Male', '46948 Rigney Plaza', true),
('Aurlie', 'Cartmer', 'Female', '29 Walton Street', true),
('Raphael', 'Winstanley', 'Male', '87 Melvin Crossing', true),
('Ken', 'Tunney', 'Male', '04 Johnson Parkway', true),
('Meta', 'Longdon', 'Female', '00 Carioca Point', false),
('Demetrius', 'Torbeck', 'Male', '4715 Heath Court', false),
('Rip', 'Baitey', 'Male', '62 Merchant Park', false),
('Clemmie', 'Danbye', 'Female', '0173 Laurel Place', false),
('Alexis', 'Spore', 'Female', '5820 Ruskin Lane', true),
('Conchita', 'Attril', 'Female', '2 Cascade Pass', true),
('Drake', 'Gambles', 'Male', '3493 Wayridge Court', false),
('Caria', 'Assel', 'Female', '423 Reinke Park', true),
('Sabrina', 'Dealy', 'Female', '647 Waubesa Park', true),
('Peirce', 'Vanyashkin', 'Male', '7614 Hermina Way', false),
('Kiley', 'Golsworthy', 'Female', '51 Lake View Road', true),
('Lenci', 'Semkins', 'Male', '2 Sunbrook Avenue', true),
('Candie', 'Castlake', 'Female', '7136 Susan Court', false),
('Sigismondo', 'Kyberd', 'Male', '21 Sachtjen Circle', true),
('Mela', 'Cuddihy', 'Female', '543 Dwight Court', false),
('Farlee', 'Birnie', 'Male', '4531 Marcy Alley', false),
('Lizette', 'Scawen', 'Female', '95 8th Point', false),
('Kenton', 'Lethardy', 'Male', '587 Blue Bill Park Parkway', false),
('Pippo', 'Borer', 'Male', '92055 Comanche Pass', true),
('Drucie', 'Feaster', 'Female', '78 Westend Parkway', false),
('Micheal', 'Vaune', 'Male', '58 Vermont Alley', true),
('Kriste', 'Dietz', 'Female', '2190 Meadow Valley Circle', false),
('Ophelia', 'Melbert', 'Female', '49147 Pawling Park', false),
('Cullen', 'Sulman', 'Male', '34 Boyd Alley', true),
('Caprice', 'Knapper', 'Female', '168 Maywood Hill', true),
('Joachim', 'Bamber', 'Male', '6058 Mcbride Circle', false),
('Mitchell', 'Wratten', 'Male', '80827 Hollow Ridge Hill', false),
('Perla', 'Stapforth', 'Female', '7931 Jackson Park', false),
('Auberon', 'Theobold', 'Male', '17 Independence Court', true),
('Latashia', 'Kenington', 'Female', '06 Oak Way', true),
('Friederike', 'Chittim', 'Female', '8 Farmco Trail', false),
('Joshua', 'McGuffog', 'Male', '48280 Farwell Avenue', false),
('Dusty', 'Neubigin', 'Male', '8085 Rutledge Court', false),
('Joana', 'Skym', 'Female', '09 Golden Leaf Road', true),
('Angel', 'Byfield', 'Male', '99326 Monterey Center', true),
('Marchall', 'Blakeley', 'Female', '18664 Steensland Crossing', false),
('Marie', 'Pinel', 'Male', '3029 Meadow Valley Plaza', true),
('Flin', 'Denford', 'Male', '1671 Hooker Court', false),
('Irwin', 'Cobbled', 'Female', '29257 Northfield Point', false),
('Leona', 'Thundercliffe', 'Female', '5 Pond Court', false),
('Roxane', 'O''Finan', 'Female', '1636 Hansons Center', false),
('Layne', 'Fielding', 'Female', '0600 Shelley Pass', true),
('Everard', 'Menendez', 'Male', '285 Westerfield Pass', false);